name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and Push Backend Image
        run: |
          docker build -t backend-app ./backend
          docker tag backend-app asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/drug-testing-repo/backend-app:latest
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/drug-testing-repo/backend-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend-service \
            --image=asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/drug-testing-repo/backend-app:latest \
            --platform=managed \
            --region=asia-south1 \
            --allow-unauthenticated